# Generated by Django 5.0.1 on 2024-01-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBdd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='workforce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
