# Generated by Django 5.0.1 on 2024-01-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBdd', '0002_alter_prospect_workforce'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prospect',
            table='Prospect',
        ),
    ]
