# Generated by Django 5.0.1 on 2024-01-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBdd', '0003_alter_prospect_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prospect',
            table='prospect',
        ),
    ]
