# Generated by Django 5.0.1 on 2024-01-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBdd', '0006_alter_prospect_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='sector',
            field=models.CharField(max_length=300),
        ),
    ]
