# Generated by Django 5.0.1 on 2024-01-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBdd', '0007_alter_prospect_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='revenue',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
