# Generated by Django 5.0.1 on 2024-01-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBdd', '0010_alter_prospect_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='direct_line',
            field=models.CharField(blank=True, default='Valeur par défaut', max_length=255),
        ),
    ]
