# Generated by Django 5.0.1 on 2024-01-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBdd', '0011_alter_prospect_direct_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='workforce',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
