# Generated by Django 5.0.1 on 2024-01-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBdd', '0012_alter_prospect_workforce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='address_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='naf_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='revenue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
